version: '3.8'

services:
  money-mule-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITROLL_API_KEY=${GITROLL_API_KEY}
      - GITROLL_API_URL=${GITROLL_API_URL:-https://gitroll.io/api/user-scan}
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
      - MAX_FILE_SIZE=52428800
      - UPLOAD_DIR=./uploads
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 